In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./smart_grid_dataset.csv")
df

,Timestamp,Voltage (V),Current (A),Power Consumption (kW),Reactive Power (kVAR),Power Factor,Solar Power (kW),Wind Power (kW),Grid Supply (kW),Voltage Fluctuation (%),Overload Condition,Transformer Fault,Temperature (°C),Humidity (%),Electricity Price (USD/kWh),Predicted Load (kW)
0,2024-01-01 00:00:00,232.483571,5.124673,1.191402,0.399029,0.907766,46.614845,26.399566,0.000000,1.055937,0,0,17.842767,64.523353,0.416156,1.233158
1,2024-01-01 00:15:00,229.308678,22.213519,5.093753,1.248030,0.831813,6.907170,18.555011,0.000000,-3.910902,1,0,18.753698,49.671940,0.492334,5.247824
2,2024-01-01 00:30:00,233.238443,46.132217,10.759806,2.790464,0.999005,15.477640,12.905025,0.000000,-0.197551,0,0,16.719325,48.472769,0.427785,10.580278
3,2024-01-01 00:45:00,237.615149,47.648972,11.322118,1.956965,0.896462,35.746398,28.937129,0.000000,2.671921,0,0,15.364564,75.766776,0.487953,11.225946
4,2024-01-01 01:00:00,228.829233,7.410166,1.695663,0.624718,0.870681,27.555038,14.184648,0.000000,3.826937,0,0,38.760333,61.384213,0.290078,1.696639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2025-06-04 18:45:00,230.283995,34.885717,8.033622,1.412623,0.958675,3.846010,3.773607,0.414005,2.032808,0,0,17.569583,65.013656,0.445045,7.866108
49996,2025-06-04 19:00:00,229.875386,7.380088,1.696501,0.308268,0.907014,16.522504,10.832262,0.000000,-3.274382,0,0,31.907835,25.049143,0.342882,1.753542
49997,2025-06-04 19:15:00,232.500424,43.166952,10.036335,1.631748,0.913899,37.235774,12.475871,0.000000,1.810338,1,0,12.606985,62.469951,0.215314,9.947611
49998,2025-06-04 19:30:00,231.326077,46.254150,10.699791,1.712672,0.948393,22.098785,1.512796,0.000000,1.500918,0,0,26.773676,58.100487,0.147162,10.886454
49999,2025-06-04 19:45:00,237.579055,17.904864,4.253821,1.050729,0.939617,7.220105,24.808317,0.000000,-1.584342,0,0,15.083737,43.051294,0.360774,4.361657

In [3]:
df.isna().sum()

Timestamp                      0
Voltage (V)                    0
Current (A)                    0
Power Consumption (kW)         0
Reactive Power (kVAR)          0
Power Factor                   0
Solar Power (kW)               0
Wind Power (kW)                0
Grid Supply (kW)               0
Voltage Fluctuation (%)        0
Overload Condition             0
Transformer Fault              0
Temperature (°C)               0
Humidity (%)                   0
Electricity Price (USD/kWh)    0
Predicted Load (kW)            0
dtype: int64

In [4]:
df.select_dtypes(include="number").where(lambda x: x < 0).count()

Voltage (V)                        0
Current (A)                        0
Power Consumption (kW)             0
Reactive Power (kVAR)              0
Power Factor                       0
Solar Power (kW)                   0
Wind Power (kW)                    0
Grid Supply (kW)                   0
Voltage Fluctuation (%)        25052
Overload Condition                 0
Transformer Fault                  0
Temperature (°C)                   0
Humidity (%)                       0
Electricity Price (USD/kWh)        0
Predicted Load (kW)                0
dtype: int64

In [5]:
print(df.dtypes)

Timestamp                          str
Voltage (V)                    float64
Current (A)                    float64
Power Consumption (kW)         float64
Reactive Power (kVAR)          float64
Power Factor                   float64
Solar Power (kW)               float64
Wind Power (kW)                float64
Grid Supply (kW)               float64
Voltage Fluctuation (%)        float64
Overload Condition               int64
Transformer Fault                int64
Temperature (°C)               float64
Humidity (%)                   float64
Electricity Price (USD/kWh)    float64
Predicted Load (kW)            float64
dtype: object

In [6]:
df["Transformer Fault"].describe()

count    50000.000000
mean         0.029200
std          0.168368
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Transformer Fault, dtype: float64

In [7]:
df["Overload Condition"].describe()

count    50000.000000
mean         0.099120
std          0.298826
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Overload Condition, dtype: float64

In [8]:
df["Grid Zone"] = [chr(65 + (i % 2)) for i in range(len(df))]
df["Meter ID"] = [f"M{(i %20) + 1:03d}" for i in range(len(df))]
df

,Timestamp,Voltage (V),Current (A),Power Consumption (kW),Reactive Power (kVAR),Power Factor,Solar Power (kW),Wind Power (kW),Grid Supply (kW),Voltage Fluctuation (%),Overload Condition,Transformer Fault,Temperature (°C),Humidity (%),Electricity Price (USD/kWh),Predicted Load (kW),Grid Zone,Meter ID
0,2024-01-01 00:00:00,232.483571,5.124673,1.191402,0.399029,0.907766,46.614845,26.399566,0.000000,1.055937,0,0,17.842767,64.523353,0.416156,1.233158,A,M001
1,2024-01-01 00:15:00,229.308678,22.213519,5.093753,1.248030,0.831813,6.907170,18.555011,0.000000,-3.910902,1,0,18.753698,49.671940,0.492334,5.247824,B,M002
2,2024-01-01 00:30:00,233.238443,46.132217,10.759806,2.790464,0.999005,15.477640,12.905025,0.000000,-0.197551,0,0,16.719325,48.472769,0.427785,10.580278,A,M003
3,2024-01-01 00:45:00,237.615149,47.648972,11.322118,1.956965,0.896462,35.746398,28.937129,0.000000,2.671921,0,0,15.364564,75.766776,0.487953,11.225946,B,M004
4,2024-01-01 01:00:00,228.829233,7.410166,1.695663,0.624718,0.870681,27.555038,14.184648,0.000000,3.826937,0,0,38.760333,61.384213,0.290078,1.696639,A,M005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2025-06-04 18:45:00,230.283995,34.885717,8.033622,1.412623,0.958675,3.846010,3.773607,0.414005,2.032808,0,0,17.569583,65.013656,0.445045,7.866108,B,M016
49996,2025-06-04 19:00:00,229.875386,7.380088,1.696501,0.308268,0.907014,16.522504,10.832262,0.000000,-3.274382,0,0,31.907835,25.049143,0.342882,1.753542,A,M017
49997,2025-06-04 19:15:00,232.500424,43.166952,10.036335,1.631748,0.913899,37.235774,12.475871,0.000000,1.810338,1,0,12.606985,62.469951,0.215314,9.947611,B,M018
49998,2025-06-04 19:30:00,231.326077,46.254150,10.699791,1.712672,0.948393,22.098785,1.512796,0.000000,1.500918,0,0,26.773676,58.100487,0.147162,10.886454,A,M019
49999,2025-06-04 19:45:00,237.579055,17.904864,4.253821,1.050729,0.939617,7.220105,24.808317,0.000000,-1.584342,0,0,15.083737,43.051294,0.360774,4.361657,B,M020

In [9]:
import itertools

# Household patterns for each zone
patterns = {
    "A": (
        ["H001"] * 2 +
        [f"H{i:03d}" for i in range(2, 9)]
    ),

    "B": (
        ["H010"] * 3 +
        ["H011"] * 2 +
        [f"H{i:03d}" for i in range(12, 17)]
    ),
}

# Assign household IDs within each zone, repeating the pattern
df["Household ID"] = None

for zone, pattern in patterns.items():
    mask = df["Grid Zone"] == zone
    n = mask.sum()
    df.loc[mask, "Household ID"] = list(
        itertools.islice(itertools.cycle(pattern), n)
    )

In [10]:
df

,Timestamp,Voltage (V),Current (A),Power Consumption (kW),Reactive Power (kVAR),Power Factor,Solar Power (kW),Wind Power (kW),Grid Supply (kW),Voltage Fluctuation (%),Overload Condition,Transformer Fault,Temperature (°C),Humidity (%),Electricity Price (USD/kWh),Predicted Load (kW),Grid Zone,Meter ID,Household ID
0,2024-01-01 00:00:00,232.483571,5.124673,1.191402,0.399029,0.907766,46.614845,26.399566,0.000000,1.055937,0,0,17.842767,64.523353,0.416156,1.233158,A,M001,H001
1,2024-01-01 00:15:00,229.308678,22.213519,5.093753,1.248030,0.831813,6.907170,18.555011,0.000000,-3.910902,1,0,18.753698,49.671940,0.492334,5.247824,B,M002,H010
2,2024-01-01 00:30:00,233.238443,46.132217,10.759806,2.790464,0.999005,15.477640,12.905025,0.000000,-0.197551,0,0,16.719325,48.472769,0.427785,10.580278,A,M003,H001
3,2024-01-01 00:45:00,237.615149,47.648972,11.322118,1.956965,0.896462,35.746398,28.937129,0.000000,2.671921,0,0,15.364564,75.766776,0.487953,11.225946,B,M004,H010
4,2024-01-01 01:00:00,228.829233,7.410166,1.695663,0.624718,0.870681,27.555038,14.184648,0.000000,3.826937,0,0,38.760333,61.384213,0.290078,1.696639,A,M005,H002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2025-06-04 18:45:00,230.283995,34.885717,8.033622,1.412623,0.958675,3.846010,3.773607,0.414005,2.032808,0,0,17.569583,65.013656,0.445045,7.866108,B,M016,H014
49996,2025-06-04 19:00:00,229.875386,7.380088,1.696501,0.308268,0.907014,16.522504,10.832262,0.000000,-3.274382,0,0,31.907835,25.049143,0.342882,1.753542,A,M017,H005
49997,2025-06-04 19:15:00,232.500424,43.166952,10.036335,1.631748,0.913899,37.235774,12.475871,0.000000,1.810338,1,0,12.606985,62.469951,0.215314,9.947611,B,M018,H015
49998,2025-06-04 19:30:00,231.326077,46.254150,10.699791,1.712672,0.948393,22.098785,1.512796,0.000000,1.500918,0,0,26.773676,58.100487,0.147162,10.886454,A,M019,H006
49999,2025-06-04 19:45:00,237.579055,17.904864,4.253821,1.050729,0.939617,7.220105,24.808317,0.000000,-1.584342,0,0,15.083737,43.051294,0.360774,4.361657,B,M020,H016

In [11]:
# rename Electricity Price (USD/kWh) to Tarrif Rate (USD/kWh)
df["Tariff Rate (USD/kWh)"] = df["Electricity Price (USD/kWh)"]
df = df.drop(columns=["Electricity Price (USD/kWh)"])

In [12]:
df["Timestamp"] = df["Timestamp"].repeat(20).iloc[:50000].reset_index(drop=True)
df

,Timestamp,Voltage (V),Current (A),Power Consumption (kW),Reactive Power (kVAR),Power Factor,Solar Power (kW),Wind Power (kW),Grid Supply (kW),Voltage Fluctuation (%),Overload Condition,Transformer Fault,Temperature (°C),Humidity (%),Predicted Load (kW),Grid Zone,Meter ID,Household ID,Tariff Rate (USD/kWh)
0,2024-01-01 00:00:00,232.483571,5.124673,1.191402,0.399029,0.907766,46.614845,26.399566,0.000000,1.055937,0,0,17.842767,64.523353,1.233158,A,M001,H001,0.416156
1,2024-01-01 00:00:00,229.308678,22.213519,5.093753,1.248030,0.831813,6.907170,18.555011,0.000000,-3.910902,1,0,18.753698,49.671940,5.247824,B,M002,H010,0.492334
2,2024-01-01 00:00:00,233.238443,46.132217,10.759806,2.790464,0.999005,15.477640,12.905025,0.000000,-0.197551,0,0,16.719325,48.472769,10.580278,A,M003,H001,0.427785
3,2024-01-01 00:00:00,237.615149,47.648972,11.322118,1.956965,0.896462,35.746398,28.937129,0.000000,2.671921,0,0,15.364564,75.766776,11.225946,B,M004,H010,0.487953
4,2024-01-01 00:00:00,228.829233,7.410166,1.695663,0.624718,0.870681,27.555038,14.184648,0.000000,3.826937,0,0,38.760333,61.384213,1.696639,A,M005,H002,0.290078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2024-01-27 00:45:00,230.283995,34.885717,8.033622,1.412623,0.958675,3.846010,3.773607,0.414005,2.032808,0,0,17.569583,65.013656,7.866108,B,M016,H014,0.445045
49996,2024-01-27 00:45:00,229.875386,7.380088,1.696501,0.308268,0.907014,16.522504,10.832262,0.000000,-3.274382,0,0,31.907835,25.049143,1.753542,A,M017,H005,0.342882
49997,2024-01-27 00:45:00,232.500424,43.166952,10.036335,1.631748,0.913899,37.235774,12.475871,0.000000,1.810338,1,0,12.606985,62.469951,9.947611,B,M018,H015,0.215314
49998,2024-01-27 00:45:00,231.326077,46.254150,10.699791,1.712672,0.948393,22.098785,1.512796,0.000000,1.500918,0,0,26.773676,58.100487,10.886454,A,M019,H006,0.147162
49999,2024-01-27 00:45:00,237.579055,17.904864,4.253821,1.050729,0.939617,7.220105,24.808317,0.000000,-1.584342,0,0,15.083737,43.051294,4.361657,B,M020,H016,0.360774

In [13]:
df.to_csv("./smart_grid_dataset_new.csv", index=False)

In [14]:
df = (
    df.sort_values(["Timestamp", "Grid Zone", "Household ID", "Meter ID"])
      .set_index(["Timestamp", "Grid Zone", "Household ID", "Meter ID"])
)

display(df)

                                                     Voltage (V)  Current (A)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001       232.483571     5.124673
                                           M003       233.238443    46.132217
                                           M019       225.459880    31.539438
                              H002         M005       228.829233     7.410166
                              H003         M007       237.896064     5.219166
...                                                          ...          ...
2024-01-27 00:45:00 B         H012         M012       226.309378    24.782440
                              H013         M014       237.550602    31.337874
                              H014         M016       230.283995    34.885717
                              H015         M018       232.500424    43.166952
                              H016         M020       237.579055    17.904864

                                                     Power Consumption (kW)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                    1.191402
                                           M003                   10.759806
                                           M019                    7.110878
                              H002         M005                    1.695663
                              H003         M007                    1.241619
...                                                                     ...
2024-01-27 00:45:00 B         H012         M012                    5.608499
                              H013         M014                    7.444331
                              H014         M016                    8.033622
                              H015         M018                   10.036335
                              H016         M020                    4.253821

                                                     Reactive Power (kVAR)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                   0.399029
                                           M003                   2.790464
                                           M019                   2.636328
                              H002         M005                   0.624718
                              H003         M007                   0.368005
...                                                                    ...
2024-01-27 00:45:00 B         H012         M012                   0.711535
                              H013         M014                   1.897054
                              H014         M016                   1.412623
                              H015         M018                   1.631748
                              H016         M020                   1.050729

                                                     Power Factor  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001          0.907766
                                           M003          0.999005
                                           M019          0.997138
                              H002         M005          0.870681
                              H003         M007          0.962855
...                                                           ...
2024-01-27 00:45:00 B         H012         M012          0.956083
                              H013         M014          0.857642
                              H014         M016          0.958675
                              H015         M018          0.913899
                              H016         M020          0.939617

                                                     Solar Power (kW)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001             46.614845
                                           M003             15.477640
                                           M019             28.074937
                              H002         M005             27.555038
                              H003         M007             21.536427
...                                                               ...
2024-01-27 00:45:00 B         H012         M012             18.141997
                              H013         M014              1.064569
                              H014         M016              3.846010
                              H015         M018             37.235774
                              H016         M020              7.220105

                                                     Wind Power (kW)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001            26.399566
                                           M003            12.905025
                                           M019            29.360392
                              H002         M005            14.184648
                              H003         M007            13.128721
...                                                              ...
2024-01-27 00:45:00 B         H012         M012            14.766407
                              H013         M014            10.137503
                              H014         M016             3.773607
                              H015         M018            12.475871
                              H016         M020            24.808317

                                                     Grid Supply (kW)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001              0.000000
                                           M003              0.000000
                                           M019              0.000000
                              H002         M005              0.000000
                              H003         M007              0.000000
...                                                               ...
2024-01-27 00:45:00 B         H012         M012              0.000000
                              H013         M014              0.000000
                              H014         M016              0.414005
                              H015         M018              0.000000
                              H016         M020              0.000000

                                                     Voltage Fluctuation (%)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                     1.055937
                                           M003                    -0.197551
                                           M019                    -2.981822
                              H002         M005                     3.826937
                              H003         M007                    -0.800185
...                                                                      ...
2024-01-27 00:45:00 B         H012         M012                    -4.756450
                              H013         M014                     1.630708
                              H014         M016                     2.032808
                              H015         M018                     1.810338
                              H016         M020                    -1.584342

                                                     Overload Condition  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                       0
                                           M003                       0
                                           M019                       0
                              H002         M005                       0
                              H003         M007                       1
...                                                                 ...
2024-01-27 00:45:00 B         H012         M012                       0
                              H013         M014                       0
                              H014         M016                       0
                              H015         M018                       1
                              H016         M020                       0

                                                     Transformer Fault  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                      0
                                           M003                      0
                                           M019                      0
                              H002         M005                      0
                              H003         M007                      0
...                                                                ...
2024-01-27 00:45:00 B         H012         M012                      0
                              H013         M014                      0
                              H014         M016                      0
                              H015         M018                      0
                              H016         M020                      0

                                                     Temperature (°C)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001             17.842767
                                           M003             16.719325
                                           M019             37.135344
                              H002         M005             38.760333
                              H003         M007             31.406756
...                                                               ...
2024-01-27 00:45:00 B         H012         M012             23.195168
                              H013         M014             11.714018
                              H014         M016             17.569583
                              H015         M018             12.606985
                              H016         M020             15.083737

                                                     Humidity (%)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001         64.523353
                                           M003         48.472769
                                           M019         35.433410
                              H002         M005         61.384213
                              H003         M007         74.001033
...                                                           ...
2024-01-27 00:45:00 B         H012         M012         31.517763
                              H013         M014         63.909446
                              H014         M016         65.013656
                              H015         M018         62.469951
                              H016         M020         43.051294

                                                     Predicted Load (kW)  \
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                 1.233158
                                           M003                10.580278
                                           M019                 6.876800
                              H002         M005                 1.696639
                              H003         M007                 1.229065
...                                                                  ...
2024-01-27 00:45:00 B         H012         M012                 5.329188
                              H013         M014                 7.496818
                              H014         M016                 7.866108
                              H015         M018                 9.947611
                              H016         M020                 4.361657

                                                     Tariff Rate (USD/kWh)
Timestamp           Grid Zone Household ID Meter ID
2024-01-01 00:00:00 A         H001         M001                   0.416156
                                           M003                   0.427785
                                           M019                   0.281159
                              H002         M005                   0.290078
                              H003         M007                   0.255648
...                                                                    ...
2024-01-27 00:45:00 B         H012         M012                   0.258863
                              H013         M014                   0.457760
                              H014         M016                   0.445045
                              H015         M018                   0.215314
                              H016         M020                   0.360774

[50000 rows x 15 columns]